### PR TITLE
sledujuserialy.cz: Rewrite addon

### PR DESCRIPTION
**Pull request by lubo**
Since this addon was old and practically non-functional, there was a need to rewrite it. Everything addon-related should work again.

### CODE REVIEW

**Comment by lubo** [comment]
No comment here ?

**Comment by lzoubek** [comment]
Thanks for your work .. I did't have time to look and test, I'll include and release soon.

**Comment by lzoubek** [comment]
Zkousel jsem oba pluginy a funguji dobre co se tyka prochazeni obsahu. Zadnym z nich jsem ale nebyl schopnej neco prehrat - a to jsem toho vyzkousel docela dost. pro sledujuserialy.cz bude pak treba pridat dalsi resolvery (nebo opravit stavajici), pro teevee.sk netusim. Nepridal bys alespon resolver pro teevee.sk? Nema cenu takovy plugin releasovat, kdyz nic neprehraje

**Comment by lubo** [comment]
Mam v plane pridat dalsie servery do resolverov, avsak v samostatnych commitoch. V kazdom pripade, Top Gear seria 10. funguje s oboma pluginmi, napriklad.

**Pull request merged**
